#ifndef SYSTEMVERSION_H
#define SYSTEMVERSION_H

#define HW_NODEMCU32 1
#define HW_ESP32_C3_LCDKIT 2
#define ESP32_2424S012 3

#define TOSTR_(x...) #x
#define STRINGIFY(x) TOSTR_(x)
#define HARDWARE_ID_STR STRINGIFY(HARDWARE_ID)
#define ORIENTATION_STR STRINGIFY(ORIENTATION)
#define BRANCH_NAME_STR STRINGIFY(BRANCH_NAME)
#define FIRMWARE_VERSION_STR STRINGIFY(FIRMWARE_VERSION)

// #define HARDWARE_ID ESP32_2424S012
// #define HARDWARE_ID HW_ESP32_C3_LCDKIT
// #define ORIENTATION SOUTH_UP
#define BUILD_DATE __DATE__
#define BUILD_TIME __TIME__

#endif // SYSTEMVERSION_H